const express = require("express");
const asyncHandler = require("express-async-handler");
const router = express.Router();
const userController = require("../app/Controllers/userCtrl");
const { authMiddleware, isAdmin } = require("../app/middlewares/authMiddleware");
router.post("/register", asyncHandler(userController.createUserCtrl));
router.post("/forgot-password-token", asyncHandler(userController.forgotPasswordToken));
router.patch("/reset-password/:token", asyncHandler(userController.resetPassword));
router.patch("/password", authMiddleware, asyncHandler(userController.updatePassword));
router.post("/login", asyncHandler(userController.loginUserCtrl));
router.get("/all-users", asyncHandler(userController.getAllUser));
router.get("/refresh", asyncHandler(userController.handleRefreshToken));
router.get("/logout", asyncHandler(userController.logout));
router.get("/:id", authMiddleware, isAdmin, asyncHandler(userController.getAUser));
router.delete("/:id", asyncHandler(userController.deleteAUser));
router.put("/edit-user", authMiddleware, asyncHandler(userController.updateAUser));
router.patch("/block-user/:id", authMiddleware, isAdmin, asyncHandler(userController.blockUser));
router.patch("/unblock-user/:id", authMiddleware, isAdmin, asyncHandler(userController.unBlockUser));
module.exports = router;
